export enum AppointmentStatus {
  PENDING = 'PENDING',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  ARRIVED = 'ARRIVED',
  NO_SHOW = 'NO_SHOW',
  DELETED = 'DELETED',
  EXECUTED = 'EXECUTED',
}