export enum NotificationTrigger {
    APPOINTMENT_BOOKED = 'APPOINTMENT_BOOKED',
    APPOINTMENT_CONFIRMED = 'APPOINTMENT_CONFIRMED',
    APPOINTMENT_RESCHEDULED = 'APPOINTMENT_RESCHEDULED',
    APPOINTMENT_CANCELED = 'APPOINTMENT_CANCELED',
    APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
    POST_VISIT_THANK_YOU = 'POST_VISIT_THANK_YOU',
    TASK_REMINDER = 'TASK_REMINDER',
    EXECUTION_NOTIFICATION = 'EXECUTION_NOTIFICATION',
    WELCOME_CREDENTIALS = 'WELCOME_CREDENTIALS',
}
